# Generated by Django 2.0.2 on 2018-03-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towguideline', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tows',
            new_name='Tow',
        ),
    ]
