# Generated by Django 2.0.2 on 2018-03-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tow', models.TextField()),
                ('priceperkms', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('hook', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('dollies', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=True)),
            ],
        ),
    ]
