# Generated by Django 2.0.2 on 2018-03-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180305_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product1',
            new_name='Product',
        ),
    ]
